baseURL = 'https://m7dhq.net/'
languageCode = 'en-uk'
title = 'M7DHQ.NET'
theme = "hugo-theme-console"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"

enableGitInfo = true

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
